name: Deploy Vue 3 Vite to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Enable Corepack (yarn)
      - name: Enable Corepack
        run: corepack enable

      # 3. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4. Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 5. Build project
      - name: Build project
        run: yarn build

      # 6. Copy index.html → 404.html (SPA fallback)
      - name: SPA fallback for GitHub Pages
        run: cp dist/index.html dist/404.html

      # 7. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: yarn deploy
